name: SotaAndRadio
version: '${project.version}'
main: ru.yoricya.privat.sota.sotaandradio.SotaAndRadio
api-version: 1.19
commands:
  sotaandradio:
    description: Информация о плагине
    permission: sotaradio

  newSota:
    description: Создает новую соту
    permission: sotaradio.newsota

  delSota:
    description: Удаляет соту
    permission: sotaradio.delsota

  nearSota:
    description: Соты поблизости
    permission: sotaradio.nearsota

  userParams:
    description: Параметры игрока
    permission: sotaradio.userparams

  infoMobileNetwork:
    description: Инфо по текущей соте
    permission: sotaradio.infomobilenetwork

  helpSota:
    description: Инфо по командам
    permission: sotaradio.helpsota

  newPhone:
    description: Создает телефон
    permission: sotaradio.newphone

  infoPhone:
    description: Информация о телефоне
    permission: sotaradio.infophone

  delPhone:
    description: Удаляет телефон
    permission: sotaradio.delphone

  rdsSearch:
    description: Поиск FM радио
    permission: sotaradio.rdssearch

